### ISSUE TITLE
JWT Tokens

### ISSUE THREAD

**Issue by LeTomJones** [GiessC/sweep#28]
Creating JWT tokens means we need proper authentication. So I see a couple problems here. We need to setup cognito and make our endpoints authenticate users through there. When a user signs in they get a JWT token, I'm sure there is a decent library for handling this. The JWT token gets them access to specific functions, there are probably decorators for this. They also contain information that can be decoded and used to verify requests. They should be pretty simple since we don't have much of a roles system (User - someone with an account, Moderator).

**Comment by GiessC** [comment]
Add Administrator to the list

**Comment by GiessC** [comment]
See #37
